import { Project } from "../../types/Interface";

const initialProject: Project = {
  projectName: "",
  projectId: "",
  estimatedBy: "",
  estimationDate: "",
  verifiedBy: "",
  verificationDate: "",
  estStart: "",
  estEns: "",
  teamSize: 0,
  timeBudget: 0,
  effort: 0,
  sections: [
    {
      sectionId: "",
      name: "Frontend development",
      minMd: 0,
      minMdFormula: "",
      maxMd: 0,
      maxMdFormula: "",
      predictedMd: 0,
      predictedMdFormula: "",
      risk: 0,
      riskFormula: "",
      tasks: [],
    },
    {
      sectionId: "",
      name: "Backend development",
      minMd: 0,
      minMdFormula: "",
      maxMd: 0,
      maxMdFormula: "",
      predictedMd: 0,
      predictedMdFormula: "",
      risk: 0,
      riskFormula: "",
      tasks: [],
    },
    {
      sectionId: "",
      name: "Mobile development",
      minMd: 0,
      minMdFormula: "",
      maxMd: 0,
      maxMdFormula: "",
      predictedMd: 0,
      predictedMdFormula: "",
      risk: 0,
      riskFormula: "",
      tasks: [],
    },
    {
      sectionId: "",
      name: "Design / UX / UI",
      minMd: 0,
      minMdFormula: "",
      maxMd: 0,
      maxMdFormula: "",
      predictedMd: 0,
      predictedMdFormula: "",
      risk: 0,
      riskFormula: "",
      tasks: [],
    },
    {
      sectionId: "",
      name: "Configuration / Setup / Deployment",
      minMd: 0,
      minMdFormula: "",
      maxMd: 0,
      maxMdFormula: "",
      predictedMd: 0,
      predictedMdFormula: "",
      risk: 0,
      riskFormula: "",
      tasks: [],
    },
  ],
  rawDevelopmentEffortSum: {
    name: "",
    main: {},
    parts: [],
  },
  summary: [],
  assumptions: [],
};

export default initialProject;
